/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveIndexRouteImport } from './routes/archive/index'
import { Route as ArchiveMembersRouteImport } from './routes/archive/members'
import { Route as ArchiveHistoryRouteImport } from './routes/archive/history'

const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIndexRoute = ArchiveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArchiveRoute,
} as any)
const ArchiveMembersRoute = ArchiveMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ArchiveRoute,
} as any)
const ArchiveHistoryRoute = ArchiveHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ArchiveRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/archive/history': typeof ArchiveHistoryRoute
  '/archive/members': typeof ArchiveMembersRoute
  '/archive/': typeof ArchiveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive/history': typeof ArchiveHistoryRoute
  '/archive/members': typeof ArchiveMembersRoute
  '/archive': typeof ArchiveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/archive/history': typeof ArchiveHistoryRoute
  '/archive/members': typeof ArchiveMembersRoute
  '/archive/': typeof ArchiveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/archive/history'
    | '/archive/members'
    | '/archive/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/archive/history' | '/archive/members' | '/archive'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/archive/history'
    | '/archive/members'
    | '/archive/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/': {
      id: '/archive/'
      path: '/'
      fullPath: '/archive/'
      preLoaderRoute: typeof ArchiveIndexRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/archive/members': {
      id: '/archive/members'
      path: '/members'
      fullPath: '/archive/members'
      preLoaderRoute: typeof ArchiveMembersRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/archive/history': {
      id: '/archive/history'
      path: '/history'
      fullPath: '/archive/history'
      preLoaderRoute: typeof ArchiveHistoryRouteImport
      parentRoute: typeof ArchiveRoute
    }
  }
}

interface ArchiveRouteChildren {
  ArchiveHistoryRoute: typeof ArchiveHistoryRoute
  ArchiveMembersRoute: typeof ArchiveMembersRoute
  ArchiveIndexRoute: typeof ArchiveIndexRoute
}

const ArchiveRouteChildren: ArchiveRouteChildren = {
  ArchiveHistoryRoute: ArchiveHistoryRoute,
  ArchiveMembersRoute: ArchiveMembersRoute,
  ArchiveIndexRoute: ArchiveIndexRoute,
}

const ArchiveRouteWithChildren =
  ArchiveRoute._addFileChildren(ArchiveRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
